
# file: IBERT_MGT_16G_25G.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_IBERT_MGT_16G_25G.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
set_property PACKAGE_PIN N17 [get_ports] lclk40_i]
set_property IOSTANDARD LVCMOS18 [get_ports LCLK40]
create_clock -period 25 -name lclk40 [get_ports lclk40_i]
##
##**************************************************************************
## Icon Constraints
##
set_property C_CLK_INPUT_FREQ_HZ 200000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN BD39 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN BD40 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN BC41 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN BC42 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN AY39 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN AY40 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN AW41 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN AW42 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN AT39 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN AT40 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN AR41 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN AR42 [get_ports gty_refclk1n_i[2]]
set_property PACKAGE_PIN AM39 [get_ports gty_refclk0p_i[3]]
set_property PACKAGE_PIN AM40 [get_ports gty_refclk0n_i[3]]
set_property PACKAGE_PIN AL41 [get_ports gty_refclk1p_i[3]]
set_property PACKAGE_PIN AL42 [get_ports gty_refclk1n_i[3]]
set_property PACKAGE_PIN AE41 [get_ports gty_refclk0p_i[4]]
set_property PACKAGE_PIN AE42 [get_ports gty_refclk0n_i[4]]
set_property PACKAGE_PIN AC41 [get_ports gty_refclk1p_i[4]]
set_property PACKAGE_PIN AC42 [get_ports gty_refclk1n_i[4]]
set_property PACKAGE_PIN U41 [get_ports gty_refclk0p_i[5]]
set_property PACKAGE_PIN U42 [get_ports gty_refclk0n_i[5]]
set_property PACKAGE_PIN T39 [get_ports gty_refclk1p_i[5]]
set_property PACKAGE_PIN T40 [get_ports gty_refclk1n_i[5]]
set_property PACKAGE_PIN L41 [get_ports gty_refclk0p_i[6]]
set_property PACKAGE_PIN L42 [get_ports gty_refclk0n_i[6]]
set_property PACKAGE_PIN K39 [get_ports gty_refclk1p_i[6]]
set_property PACKAGE_PIN K40 [get_ports gty_refclk1n_i[6]]
set_property PACKAGE_PIN BD13 [get_ports gty_refclk0p_i[7]]
set_property PACKAGE_PIN BD12 [get_ports gty_refclk0n_i[7]]
set_property PACKAGE_PIN BC11 [get_ports gty_refclk1p_i[7]]
set_property PACKAGE_PIN BC10 [get_ports gty_refclk1n_i[7]]
set_property PACKAGE_PIN AY13 [get_ports gty_refclk0p_i[8]]
set_property PACKAGE_PIN AY12 [get_ports gty_refclk0n_i[8]]
set_property PACKAGE_PIN AW11 [get_ports gty_refclk1p_i[8]]
set_property PACKAGE_PIN AW10 [get_ports gty_refclk1n_i[8]]
set_property PACKAGE_PIN AT13 [get_ports gty_refclk0p_i[9]]
set_property PACKAGE_PIN AT12 [get_ports gty_refclk0n_i[9]]
set_property PACKAGE_PIN AR11 [get_ports gty_refclk1p_i[9]]
set_property PACKAGE_PIN AR10 [get_ports gty_refclk1n_i[9]]
set_property PACKAGE_PIN AM13 [get_ports gty_refclk0p_i[10]]
set_property PACKAGE_PIN AM12 [get_ports gty_refclk0n_i[10]]
set_property PACKAGE_PIN AL11 [get_ports gty_refclk1p_i[10]]
set_property PACKAGE_PIN AL10 [get_ports gty_refclk1n_i[10]]
set_property PACKAGE_PIN AE11 [get_ports gty_refclk0p_i[11]]
set_property PACKAGE_PIN AE10 [get_ports gty_refclk0n_i[11]]
set_property PACKAGE_PIN AC11 [get_ports gty_refclk1p_i[11]]
set_property PACKAGE_PIN AC10 [get_ports gty_refclk1n_i[11]]
set_property PACKAGE_PIN U11 [get_ports gty_refclk0p_i[12]]
set_property PACKAGE_PIN U10 [get_ports gty_refclk0n_i[12]]
set_property PACKAGE_PIN T13 [get_ports gty_refclk1p_i[12]]
set_property PACKAGE_PIN T12 [get_ports gty_refclk1n_i[12]]
set_property PACKAGE_PIN L11 [get_ports gty_refclk0p_i[13]]
set_property PACKAGE_PIN L10 [get_ports gty_refclk0n_i[13]]
set_property PACKAGE_PIN K13 [get_ports gty_refclk1p_i[13]]
set_property PACKAGE_PIN K12 [get_ports gty_refclk1n_i[13]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_0 -period 5.0 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_0 -period 5.0 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_0 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_0 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_2 -period 5.0 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_2 -period 5.0 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_2 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_2 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_4 -period 5.0 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_4 -period 5.0 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_4 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_4 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_6 -period 5.0 [get_ports gty_refclk0p_i[3]]
create_clock -name gtrefclk1_6 -period 5.0 [get_ports gty_refclk1p_i[3]]
set_clock_groups -group [get_clocks gtrefclk0_6 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_6 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_8 -period 5.0 [get_ports gty_refclk0p_i[4]]
create_clock -name gtrefclk1_8 -period 5.0 [get_ports gty_refclk1p_i[4]]
set_clock_groups -group [get_clocks gtrefclk0_8 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_8 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_11 -period 5.0 [get_ports gty_refclk0p_i[5]]
create_clock -name gtrefclk1_11 -period 5.0 [get_ports gty_refclk1p_i[5]]
set_clock_groups -group [get_clocks gtrefclk0_11 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_11 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_14 -period 5.0 [get_ports gty_refclk0p_i[6]]
create_clock -name gtrefclk1_14 -period 5.0 [get_ports gty_refclk1p_i[6]]
set_clock_groups -group [get_clocks gtrefclk0_14 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_14 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_15 -period 5.0 [get_ports gty_refclk0p_i[7]]
create_clock -name gtrefclk1_15 -period 5.0 [get_ports gty_refclk1p_i[7]]
set_clock_groups -group [get_clocks gtrefclk0_15 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_15 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_17 -period 5.0 [get_ports gty_refclk0p_i[8]]
create_clock -name gtrefclk1_17 -period 5.0 [get_ports gty_refclk1p_i[8]]
set_clock_groups -group [get_clocks gtrefclk0_17 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_17 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_19 -period 5.0 [get_ports gty_refclk0p_i[9]]
create_clock -name gtrefclk1_19 -period 5.0 [get_ports gty_refclk1p_i[9]]
set_clock_groups -group [get_clocks gtrefclk0_19 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_19 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_21 -period 5.0 [get_ports gty_refclk0p_i[10]]
create_clock -name gtrefclk1_21 -period 5.0 [get_ports gty_refclk1p_i[10]]
set_clock_groups -group [get_clocks gtrefclk0_21 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_21 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_23 -period 5.0 [get_ports gty_refclk0p_i[11]]
create_clock -name gtrefclk1_23 -period 5.0 [get_ports gty_refclk1p_i[11]]
set_clock_groups -group [get_clocks gtrefclk0_23 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_23 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_26 -period 5.0 [get_ports gty_refclk0p_i[12]]
create_clock -name gtrefclk1_26 -period 5.0 [get_ports gty_refclk1p_i[12]]
set_clock_groups -group [get_clocks gtrefclk0_26 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_26 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_29 -period 5.0 [get_ports gty_refclk0p_i[13]]
create_clock -name gtrefclk1_29 -period 5.0 [get_ports gty_refclk1p_i[13]]
set_clock_groups -group [get_clocks gtrefclk0_29 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_29 -include_generated_clocks] -asynchronous


